STAP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main')
]

main/urls.py
from django.urls import path
from .views import STPList, SiteList, SiteDetail, STPDetail, SubSiteDetail


app_name = 'main'

urlpatterns = [
    path('stp/', STPList.as_view(), name='stp_list'),
    path('site/', SiteList.as_view(), name='site_list'),
    path('sites/', SiteList.as_view(), name='sites_list'),
    path('site/<str:nhs_code>', SiteDetail.as_view(), name='site_detail'),
    path('stp/<str:slug>', STPDetail.as_view(), name='stp_detail'),
    path('site/<str:site>/<str:nhs_code>', SubSiteDetail.as_view(), name='subsite_detail'),
]

main/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class Site(models.Model):
    name = models.CharField(max_length=100)
    stp = models.ForeignKey('STP', on_delete=models.CASCADE, verbose_name='STP')
    nhs_code = models.CharField(max_length=6, verbose_name='NHS Code', unique=True)
    street_address_1 = models.CharField(max_length=40, blank=True)
    street_address_2 = models.CharField(max_length=40, blank=True)
    city = models.CharField(max_length=20, blank=True)
    county = models.CharField(max_length=20, blank=True)
    postcode = models.CharField(max_length=10, blank=True)

    website = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('main:site_detail', kwargs={'nhs_code': self.nhs_code})


class SubSite(models.Model):
    name = models.CharField(max_length=100)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, verbose_name='Trust')
    nhs_code = models.CharField(max_length=6, verbose_name='NHS Code', unique=True)
    street_address_1 = models.CharField(max_length=40, blank=True)
    street_address_2 = models.CharField(max_length=40, blank=True)
    city = models.CharField(max_length=20, blank=True)
    county = models.CharField(max_length=20, blank=True)
    postcode = models.CharField(max_length=10, blank=True)

    website = models.CharField(max_length=100, blank=True)

    main_location = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-main_location', 'name']

    def get_absolute_url(self):
        return reverse('main:subsite_detail', kwargs={'site': self.site.nhs_code, 'nhs_code': self.nhs_code})


class STP(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'STP/Health Board'
        verbose_name_plural = 'STPs/Health Boards'

    def get_absolute_url(self):
        return reverse('main:stp_detail', args=[self.pk])


class Year(models.Model):
    year = models.IntegerField()

    def __str__(self):
        return f'{self.year}'

    class Meta:
        ordering = ['year']


class Beds(models.Model):
    general = models.IntegerField()
    critical = models.IntegerField()
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Beds'
        ordering = ['-year']

    def __str__(self):
        return f'{self.site} Beds: {self.year}'


class Income(models.Model):
    income = models.DecimalField(max_digits=20, decimal_places=2)
    forecast_surplus = models.DecimalField(max_digits=20, decimal_places=2, blank=True)

    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    site = models.ForeignKey(Site, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Income Statements'
        ordering = ['year']

    def __str__(self):
        return f'{self.site} Income: {self.year}'


class Leader(models.Model):
    first = models.CharField(max_length=20)
    last = models.CharField(max_length=20)
    nhs_code = models.ForeignKey(Site, on_delete=models.CASCADE)
    title = models.CharField(max_length=5)
    position = models.ForeignKey('Position', on_delete=models.CASCADE)


class Position(models.Model):
    c_suite = models.BooleanField(default=False)
    name = models.CharField(max_length=20)
# TODO CQC model

main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import STP, Site, SubSite, Income, Beds
import plotly.graph_objs as go
import plotly.express as px
import pandas as pd
# Create your views here.


class STPList(ListView):
    model = STP
    template_name = 'main/stp_list.html'


class SiteList(ListView):
    model = Site
    template_name = 'main/site_list.html'


class SiteDetail(DetailView):
    model = Site
    template_name = 'main/site_detail.html'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Site, nhs_code=self.kwargs['nhs_code'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get the years for the income data
        income = Income.objects.filter(site=self.object.pk)
        income_years = [x.year for x in income]
        # get the years for the bed data
        beds = Beds.objects.filter(site=self.object.pk)
        bed_years = [x.year for x in beds]
        # add the years to the context
        context['income_years'] = income_years
        context['bed_years'] = bed_years
        return context


class STPDetail(DetailView):
    model = STP
    template_name = 'main/stp_detail.html'


class SubSiteDetail(DetailView):
    model = SubSite
    template_name = 'main/subsite_detail.html'

    def get_object(self, *args, **kwargs):
        return get_object_or_404(SubSite, nhs_code=self.kwargs['nhs_code'])

main/templates/main/site_detail.html
{% extends 'components/base.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'main/style.css' %}">
{% endblock %}
{% block content %}

    <div class="col-10 md-5 mx-auto my-5 text-center">
        <h1>{{ site.name }}</h1>
        <h3>{{ site.stp }}</h3>
    </div>

    {# Map and address #}
    <div class="container card py-3 my-5">
        <div class="row">
            <div class="col-8">
                Map Goes here
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        {% if site.street_address_1 %}{{ site.street_address_1 }}<br>{% endif %}
                    </div>
                    <div class="card-body">
                        {% if site.street_address_2 %}{{ site.street_address_2 }}<br>{% endif %}
                        {% if site.city %}{{ site.city }}<br>{% endif %}
                        {% if site.county %}{{ site.county }}<br>{% endif %}
                        {% if site.postcode %}{{ site.postcode }}<br>{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {# Left column #}
            <div class="col-8">

            {# Income Data #}
                <button class="btn full btn-primary btn-block full mb-1" data-toggle="collapse" data-target="#collapseFinance"
                        type="button" aria-expanded="false" aria-controls="collapseFinance">Trust Finances</button>
                <div class="collapse table-responsive" id="collapseFinance">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Type</th>
                                    {% for year in income_years %}
                                        <th scope="col">{{ year }}</th>
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">Income</th>
                                    {% for income in site.income_set.all %}
                                        <td>{{ income.income }}</td>
                                    {% endfor %}
                                </tr>
                                <tr>
                                    <th scope="row">Surplus/Defecit</th>
                                    {% for income in site.income_set.all %}
                                        <td>{{ income.forecast_surplus }}</td>
                                    {% endfor %}
                                </tr>
                            </tbody>
                        </table>
                </div>

            {# Beds Data #}
            <button class="btn btn-primary btn-block full mb-1" data-toggle="collapse" data-target="#collapseBeds"
                    type="button" aria-expanded="false" aria-controls="collapseBeds">Beds Data</button>
                <div class="collapse table-responsive" id="collapseBeds">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Type</th>
                                    {% for year in bed_years %}
                                        <th scope="col">{{ year }}</th>
                                    {% endfor %}
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">General Care</th>
                                    {% for beds in site.beds_set.all %}
                                        <td>{{ beds.general }}</td>
                                    {% endfor %}
                                </tr>
                                <tr>
                                    <th scope="row">Critical Care</th>
                                    {% for beds in site.beds_set.all %}
                                        <td>{{ income.critical }}</td>
                                    {% endfor %}
                                </tr>
                            </tbody>
                        </table>
                </div>

            {# Workforce Data #}


            {# Sub Site Data #}
                <button class="btn btn-secondary btn-block full mb-1" data-toggle="collapse" data-target="#collapseSites"
                type="button" aria-expanded="false" aria-controls="collapseSites">Site Details</button>
                <div class="collapse" id="collapseSites">
                    <div class="card card-body">
                        {% for subsite in site.subsite_set.all %}
                            <a href="{{ subsite.get_absolute_url }}">{{ subsite.name }}</a>{% if subsite.main_location %}- Main Location{% endif %}<br>
                        {% endfor %}
                    </div>
                </div>

            </div>

            {# Right Column #}
            <div class="col-4">
                <h1>Leadership</h1>
            </div>
        </div>
    </div>

{% endblock %}

main/templates/main/site_list.html
{% extends 'components/base.html' %}

{% block content %}

    {% for site in site_list %}
        <a href="{{ site.get_absolute_url }}">{{ site.name }}</a>
    {% endfor %}

{% endblock %}

main/templates/main/stp_detail.html
{% extends 'components/base.html' %}

{% block content %}
    <h1>{{ stp.name }}</h1>
    <ul>
        {% for site in stp.site_set.all %}
            <li><a href="{{ site.get_absolute_url }}">{{ site.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

main/templates/main/stp_list.html
{% extends 'components/base.html' %}

{% block content %}

    {% for stp in stp_list %}
        <a href="{{ stp.get_absolute_url }}"><h5>{{ stp.name }}</h5></a>
        <ul>
            {% for site in stp.site_set.all %}
                <li><a href="{{ site.get_absolute_url }}">{{ site.name }}</a></li>
            {% endfor %}
        </ul>
    {% endfor %}

{% endblock %}

main/templates/main/subsite_detail.html
{% extends 'components/base.html' %}

{% block content %}
    <h1>{{ subsite.name }}</h1>
{% endblock %}

templates/components/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block stylesheet %}{% endblock %}
    <title>{% block title %}STAP Tool{% endblock %}</title>
</head>
<body>
{% block navbar %}
    {% include 'components/navbar.html' %}
{% endblock %}
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

templates/components/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <a class="navbar-brand" href="#">STAP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="post">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>